const providers = [
  {
    id: 1,
    name: "John Doe",
    businessName: "Doe Cleaning Services",
    serviceCategories: ["Cleaning Services"],
    distance: "3 km",
    rating: 4.7,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Jane Smith",
    businessName: "Smith Tailors",
    serviceCategories: ["Tailor"],
    distance: "5 km",
    rating: 4.5,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Michael Johnson",
    businessName: "Elite Mechanics",
    serviceCategories: ["Mechanic"],
    distance: "8 km",
    rating: 4.2,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Emily Davis",
    businessName: "Quick Electricians",
    serviceCategories: ["Electricians"],
    distance: "2 km",
    rating: 4.8,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "William Brown",
    businessName: "Brown Painters",
    serviceCategories: ["Painter"],
    distance: "7 km",
    rating: 4.3,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Olivia Miller",
    businessName: "Miller Cleaning Co.",
    serviceCategories: ["Cleaning Services"],
    distance: "6 km",
    rating: 4.6,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Noah Wilson",
    businessName: "Wilson Mechanics",
    serviceCategories: ["Mechanic"],
    distance: "4 km",
    rating: 4.4,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Sophia Moore",
    businessName: "Moore Tailoring",
    serviceCategories: ["Tailor"],
    distance: "3 km",
    rating: 4.5,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "James Taylor",
    businessName: "Taylor Electricians",
    serviceCategories: ["Electricians"],
    distance: "5 km",
    rating: 4.7,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Isabella Anderson",
    businessName: "Anderson Painting",
    serviceCategories: ["Painter"],
    distance: "10 km",
    rating: 4.1,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 11,
    name: "Liam Martinez",
    businessName: "Martinez Mechanics",
    serviceCategories: ["Mechanic"],
    distance: "8 km",
    rating: 4.2,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    name: "Charlotte Thomas",
    businessName: "Thomas Tailors",
    serviceCategories: ["Tailor"],
    distance: "6 km",
    rating: 4.5,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    name: "Benjamin Jackson",
    businessName: "Jackson Cleaning",
    serviceCategories: ["Cleaning Services"],
    distance: "4 km",
    rating: 4.6,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    name: "Amelia White",
    businessName: "White Electricians",
    serviceCategories: ["Electricians"],
    distance: "2 km",
    rating: 4.9,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 15,
    name: "Ethan Harris",
    businessName: "Harris Painting",
    serviceCategories: ["Painter"],
    distance: "9 km",
    rating: 4.0,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 16,
    name: "Mia Clark",
    businessName: "Clark Tailoring",
    serviceCategories: ["Tailor"],
    distance: "3 km",
    rating: 4.6,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 17,
    name: "Lucas Lewis",
    businessName: "Lewis Cleaning Co.",
    serviceCategories: ["Cleaning Services"],
    distance: "5 km",
    rating: 4.5,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 18,
    name: "Harper Lee",
    businessName: "Lee Electricians",
    serviceCategories: ["Electricians"],
    distance: "7 km",
    rating: 4.4,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 19,
    name: "Elijah Walker",
    businessName: "Walker Mechanics",
    serviceCategories: ["Mechanic"],
    distance: "8 km",
    rating: 4.3,
    pfp: "https://via.placeholder.com/150",
  },
  {
    id: 20,
    name: "Ava Hall",
    businessName: "Hall Painting Services",
    serviceCategories: ["Painter"],
    distance: "6 km",
    rating: 4.5,
    pfp: "https://via.placeholder.com/150",
  },
  // Add more entries with unique ids here
];

export default providers;
